#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
      keyid: 7EA0A9C3F273FCD8

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

users:
  - name: quickstart
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - mkdir -p /var/log/selenium-results
  - chown -R quickstart:quickstart /var/log/selenium-results
  - su quickstart -c "git clone https://gitlab.wikimedia.org/repos/test-platform/mediawiki-quickstart.git /home/quickstart/mediawiki-quickstart"
  - sleep 5
  - |
    cat > /etc/systemd/system/results-server.service << 'EOL'
    [Unit]
    Description=Simple HTTP Server for Selenium Results
    After=network.target

    [Service]
    Type=simple
    User=quickstart
    WorkingDirectory=/var/log/selenium-results
    ExecStart=/usr/bin/python3 -m http.server 8088
    Restart=always

    [Install]
    WantedBy=multi-user.target
    EOL
  - |
    cat > /etc/systemd/system/selenium-test.service << 'EOL'
    [Unit]
    Description=Continuous Selenium Test Runner
    After=network.target

    [Service]
    Type=simple
    User=quickstart
    WorkingDirectory=/home/quickstart/mediawiki-quickstart
    Environment="FORCE=1"
    Environment="SKIP_COUNTDOWN=1"
    Environment="SILENT=1"
    Environment="SKIP_LOCALIZATION_CACHE_REBUILD=1"
    Environment="SKIP_PAGE_IMPORT=1"
    Environment="RECLAIM_DISK_SPACE=1"
    Environment="OUTPUT_PATH=/var/log/selenium-results"
    ExecStart=/bin/bash -c 'sleep 30 && git pull && ./ci.components.selenium && docker compose down && sudo systemctl restart docker'
    Restart=always

    [Install]
    WantedBy=multi-user.target
    EOL
  - sleep 5
  - systemctl daemon-reload
  - systemctl enable results-server
  - systemctl start results-server
  - systemctl enable selenium-test
  - systemctl start selenium-test
  - |
    mkdir -p /etc/systemd/journald.conf.d
    cat > /etc/systemd/journald.conf.d/size-limit.conf << 'EOL'
    [Journal]
    SystemMaxUse=200M
    SystemMaxFileSize=20M
    EOL
  - systemctl restart systemd-journald
  - journalctl --vacuum-size=200M
  - apt-get clean

package_update: true
package_upgrade: true

final_message: "The system is finally up, after $UPTIME seconds"