#!/bin/bash

root="manifests"

manifests=("extensions" "skins")

for manifest in "${manifests[@]}"; do
  folders=$(find "$root/$manifest" -mindepth 1 -maxdepth 1 -type d | sort)

  for folder in $folders; do
    folder_name=$(basename "$folder")
      echo "--------------------------------------------------------------------------------"
      echo "${folder_name}"
      echo "--------------------------------------------------------------------------------"

      echo "--------------------------------------------------------------------------------"
      echo "./fresh_install"
      echo "--------------------------------------------------------------------------------"
      time FORCE=1 SKIP_COUNTDOWN=1 SKIP_SKIN=1 VERBOSE=1 ./fresh_install

      echo "--------------------------------------------------------------------------------"
      echo "./install $manifest/$folder_name"
      echo "--------------------------------------------------------------------------------"
      time VERBOSE=1 ./install "$manifest/$folder_name"

      echo "--------------------------------------------------------------------------------"
      echo "./run_selenium_tests $manifest/$folder_name"
      echo "--------------------------------------------------------------------------------"
      time VERBOSE=1 ./run_selenium_tests "$manifest/$folder_name/tests/selenium/*specs/**/*.js" ".*"
  done
done
