#!/bin/bash

GIT_CLONE_BASE_URL="https://gerrit.wikimedia.org/r/mediawiki"

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[1]}")" >/dev/null 2>&1 && pwd)"
MEDIAWIKI_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/mediawiki"
MEDIAWIKI_PORT=8080
SPECIAL_VERSION_URL="http://localhost:$MEDIAWIKI_PORT/wiki/Special:Version"
HOST_UID=$(id -u)
HOST_GID=$(id -g)

MW_ENV="
MW_DOCKER_PORT=$MEDIAWIKI_PORT
MW_DOCKER_UID=$HOST_UID
MW_DOCKER_GID=$HOST_GID
XDEBUG_CONFIG=''
"

export MW_ENV

# Prevent pre-override merge warnings
# These appear at the stage of "docker compose" calls before
# the docker-compose.override.yml values are merged
# Post-merge we have what's needed
export XDEBUG_CONFIG=''
export MW_DOCKER_GID=''
export MW_DOCKER_UID=''