#!/bin/bash

GIT_CLONE_BASE_URL="https://gerrit.wikimedia.org/r/mediawiki"

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[1]}")" >/dev/null 2>&1 && pwd)"
MEDIAWIKI_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)/mediawiki"
MEDIAWIKI_PORT=8080
SPECIAL_VERSION_URL="http://localhost:$MEDIAWIKI_PORT/wiki/Special:Version"
HOST_UID=$(id -u)
HOST_GID=$(id -g)
HOST_IP=$(ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')
# Use HOST_IP sparingly, especially inside containers

MW_ENV="
MW_DOCKER_PORT=$MEDIAWIKI_PORT
MW_DOCKER_UID=$HOST_UID
MW_DOCKER_GID=$HOST_GID
XDEBUG_CONFIG=''
HOST_IP=$HOST_IP
"

export MW_ENV