#!/bin/bash

source "./config"
source "./common/utility.sh"
source "./docker/docker.sh"
source "./stop"
source "./remove"
source "./prepare"
source "./start"
source "./import_page_xml"

fresh_install() {
  [ -d "$MEDIAWIKI_PATH" ] && cp "$SCRIPT_PATH/docker-compose.override.yml" "$MEDIAWIKI_PATH" || true
  verify_compose_version 2 || return 1
  verify_docker_group || return 1
  print_force_mode_notification_if_necessary
  if ! confirm_action "Are you sure you want to do a fresh install"; then
    return
  fi
  local extra_compose_file_path
  extra_compose_file_path=${1:-""}
  stop
  remove
  prepare "$extra_compose_file_path"
  start
  import_page_xml "/tmp/page-xml"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  fresh_install "$@"
fi
