#!/bin/bash

# set -x

import_page_xml() {
    local folder="$1"
    docker exec -u "$HOST_UID:$HOST_GID" -i mediawiki-mediawiki-1 bash /import_page_xml.sh "$folder"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    import_page_xml "$@"
fi