#!/bin/bash

source "./docker.sh"
source "./config"
source "./open_special_version_page"

run_service_setup_for_components() {
  # Execute any setup scripts found for services defined in component
  # docker-compose.yml files
  #
  # ie if inside "extensions/Elastica/docker-compose.yml" we defined an
  # "elasticsearch" service, we may need to run some setup command after
  # that service is started. Quickstart makes this easy, just place such
  # commands in a "extensions/Elastica/setup.elasticsearch.sh" file
  #
  # For every component being installed, this function runs such setup
  # scripts, if found, in their respective containers
  local needs_restart=false
  for component in "$@"; do
    for host_script in "$component"/setup.*.sh; do
      [ -e "$host_script" ] || continue
      local service_name=$(basename "$host_script" .sh | cut -d. -f2)
      if ! is_service_running "$service_name"; then
        echo -e "Warning: Found setup script '$host_script', but service '$service_name' is not running\nIs '$service_name' defined in '$component/docker-compose.yml'? Skipping..."
        continue
      fi
      chmod +x "$host_script"
      # Ensure /var/local exists, just in case
      ./shellto -u root "$service_name" mkdir -p "/var/local/$(dirname "$host_script")" || exit 1
      # Copy script into container's /var/local
      docker compose cp "$host_script" "$service_name":"/var/local/$host_script"
      # Execute it
      ./shellto -u root "$service_name" "/var/local/$host_script"
      needs_restart=true
    done
  done
  [ "$needs_restart" = true ]
  return
}

install() {
  if ! is_service_running "mediawiki"; then
    echo "MediaWiki container is not running"
    exit 1
  fi
  export GIT_CLONE_BASE_URL

  local components=$(./shellto -e VERBOSE m /var/local/common/hydrate_dependencies_list "$@")
  if [ -z "$components" ]; then
    echo "All requested components already installed"
    return 0
  fi

  # Installation steps that need to happen before component docker-compose.yml services are brought up
  ./shellto -e VERBOSE -e GIT_CLONE_BASE_URL -e BRANCH m /var/local/installer/prepare $components

  local install_status=$?

  if [ $install_status -eq 2 ]; then
    # No components were installed, exit normally
    return 0
  fi

  # In case components with thier own docker-compose.yml were installed, bring their services up
  docker compose up -d --wait 2>&1 | verboseOrDotPerLine "Docker compose up ( for any component containers )" || exit 1

  # Installation steps that need to happen after component docker-compose.yml services are brought up
  # ( install is split into 'prepare'/'finalize' stages so we don't have to use hacky methods to message
  # to the host the correct place to invoke 'docker compose up -d --wait' )
  ./shellto -e VERBOSE -e SKIP_LOCALIZATION_CACHE_REBUILD -e SKIP_PAGE_IMPORT -u root m /var/local/installer/finalize $components

  install_status=$?

  if [ $install_status -eq 0 ]; then
    if run_service_setup_for_components "$@"; then
      # Restart if we ran any component service setup scripts
      # Let's say "my_service" in a component docker-compose.yml did a shared volume on the
      # QuickStart .env file and its "setup.my_service.sh" wrote a new env var to that file,
      # this restart would ensure its immediate availability to all other services.
      # There are likely other scenarios where the restart would be useful too
      ./restart
    fi
    open_special_version_page
  else
    # Other error occurred
    return $install_status
  fi
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  installer_start_time=$(date +%s)
  install "$@"
  print_duration_since_start "$installer_start_time" "\n\033[32m⏲\033[0m Component installer duration: %02d:%02d"
fi