#!/bin/bash

source "./docker/docker.sh"
source "./config"
source "./open_special_version_page"

install() {
  if ! are_containers_running "mediawiki-mediawiki-web-1"; then
    echo "MediaWiki-web container is not running"
    exit 1
  fi
  export GIT_CLONE_BASE_URL
  if ./shellto -e VERBOSE -e GIT_CLONE_BASE_URL m /var/local/installer/install "$@"; then
    local installed_components=$(./shellto m cat Components.installed.txt)
    if update_compose_tracker $installed_components; then
      # Restart if components with thier own docker-compose.yml were installed
      ./restart
    fi
    open_special_version_page
  fi
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install "$@"
fi