#!/bin/bash

source "./common/utility.sh"
source "./selenium/selenium.sh"

list_selenium_tests() {
  ./shellto s sh -c "
    node -e \"
      (async () => {
        const { default: Mocha } = await import('mocha')
        const { default: fs } = await import('fs')
        const { default: path } = await import('path')
        const { pathToFileURL } = await import('url')

        const listTests = async (dir) => {
          const files = fs.readdirSync(dir)
            .filter(file => file.endsWith('.js'))

          for (const file of files) {
            const fullPath = path.join(dir, file)
            console.log(fullPath)

            const mocha = new Mocha()

            try {
              // Try CommonJS approach first
              mocha.addFile(fullPath)
              mocha.loadFiles()
            } catch (err) {
              if (err.code === 'ERR_REQUIRE_ESM') {
                // It's an ES module - import it to register tests
                await import(pathToFileURL(path.resolve(fullPath)).href)
              } else {
                throw err
              }
            }

            // Either way, tests should now be registered
            mocha.suite.eachTest(test => console.log('\\t' + test.title))
            mocha.suite.suites = []
          }
        }

        const traverseAndListTests = async dir => {
          if (fs.existsSync(dir) && fs.statSync(dir).isDirectory()) {
            if (path.basename(dir) === 'specs' && path.basename(path.dirname(dir)) === 'selenium') {
              await listTests(dir)
            } else {
              for (const subdir of fs.readdirSync(dir)) {
                await traverseAndListTests(path.join(dir, subdir))
              }
            }
          }
        }

        for (const dir of ['tests/', 'extensions/', 'skins/']) {
          await traverseAndListTests(dir)
        }
      })()
    \"
  "
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  ensure_selenium_ready || exit 1
  echo
  echo "Selenium tests:"
  echo
  list_selenium_tests "$@"
  echo
fi
