#!/bin/bash

source "./config"
source "./open_special_version_page"

make_skin_default() {
  local skin_name
  skin_name="$1"
  (
    cd "$MEDIAWIKI_PATH" || exit 1
    sed -i -E "s/\\\$wgDefaultSkin.*;[[:blank:]]*$/\\\$wgDefaultSkin = \"$skin_name\";/g" LocalSettings.php || exit 1
	sleep 1
	open_special_version_page
  ) && return 0 || return 1
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  make_skin_default "$@"
fi