#!/bin/bash

source "./config"
source "./open_special_version_page"

make_skin_default() {
  local skin_name
  skin_name="$1"
  (
    cd "$MEDIAWIKI_PATH" || exit 1
    echo -e "<?php\n\$wgDefaultSkin = \"$skin_name\";\n" > Skin.default.php
    sleep 1
    open_special_version_page
  ) && return 0 || return 1
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  make_skin_default "$@"
fi