#!/bin/bash

set -eu

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

source "$SCRIPT_PATH/utility.sh"
source "$SCRIPT_PATH/docker.sh"
source "$SCRIPT_PATH/docker-compose-wrapper.sh"

MEDIAWIKI_PATH="$SCRIPT_PATH/mediawiki"
MEDIAWIKI_PORT=8080

# shellcheck disable=SC2089
MW_ENV="
MW_DOCKER_PORT=$MEDIAWIKI_PORT
MW_DOCKER_UID=
MW_DOCKER_GID=
MEDIAWIKI_USER=Admin
MEDIAWIKI_PASSWORD=dockerpass
XDEBUG_ENABLE=true
XHPROF_ENABLE=true
XDEBUG_CONFIG=''
"

# shellcheck disable=SC2090
export MW_ENV

SPECIAL_VERSION_URL="http://localhost:$MEDIAWIKI_PORT/wiki/Special:Version"

fresh_install() {
  verify_compose_version 2 || return 1
  if ! confirm_action "Are you sure you want to do a fresh install"; then
    return
  fi
  local extra_compose_file_path
  extra_compose_file_path=${1:-""}
  stop
  remove
  prepare "$extra_compose_file_path"
  start
}

prepare() {
  local extra_compose_file_path
  extra_compose_file_path=${1:-""}
  mkdir -p "$MEDIAWIKI_PATH"
  cd "$MEDIAWIKI_PATH" || exit
  git clone https://gerrit.wikimedia.org/r/mediawiki/core.git . --depth=1
  echo "$MW_ENV" >.env
  cp "$SCRIPT_PATH/docker-compose.override.yml" . || true
  if [ -n "$extra_compose_file_path" ] && [ -f "$extra_compose_file_path" ]; then
    cp "$extra_compose_file_path" .
  fi
}

remove() {
  if [ ! -d "$MEDIAWIKI_PATH" ]; then
    return
  fi
  if ! confirm_action "Are you sure you want to delete mediawiki containers and EVERYTHING in \"$MEDIAWIKI_PATH\""; then
    exit 1
  fi
  docker_compose down
  if [ -n "$MEDIAWIKI_PATH" ] && [ -d "$MEDIAWIKI_PATH" ]; then
    rm -rf "$MEDIAWIKI_PATH"
  fi
}

stop() {
  if [ ! -d "$MEDIAWIKI_PATH" ]; then
    return
  fi
  docker_compose stop
}

start() {
  if ! is_container_present "mediawiki-mediawiki-1"; then
    # docker_compose build --no-cache
    docker_compose up -d || exit 1
    docker_compose exec mediawiki composer update
    docker_compose exec mediawiki bash /docker/install.sh
    sleep 2
    use_skin Vector
    return 0
  fi

  if ! is_container_running "mediawiki-mediawiki-1"; then
    docker_compose up -d
    sleep 1
  fi
  wait_until_url_available $SPECIAL_VERSION_URL
  open_special_version_page
}

restart() {
  stop
  sleep 2
  start
}

bash_mw() {
  docker_compose exec mediawiki bash
}

bash_jr() {
  docker_compose exec mediawiki-jobrunner bash
}

bash_wb() {
  docker_compose exec mediawiki-web bash
}

use_skin() {
  local skin_name
  skin_name=$1
  "$SCRIPT_PATH/skins/installer.sh" install "$skin_name"
  open_special_version_page
}

open_special_version_page() {
  if [ "${skipopenspecialversionpage:-false}" = "true" ]; then
    return
  fi
  open_url_when_available "$SPECIAL_VERSION_URL"
}

run_parser_tests() {
  docker_compose exec mediawiki php tests/parser/parserTests.php
}

run_php_unit_tests() {
  docker_compose exec --workdir /var/www/html/w/tests/phpunit mediawiki php phpunit.php ${testpath:+$testpath} ${testgroup:+--group $testgroup} --testdox
}

docker_compose() {
  docker_compose_wrapper "$MEDIAWIKI_PATH" "$@"
}

prepare_mediawiki_for_selenium() {
  export USE_SELENIUM_YML=true
  if ! fresh_install "$SCRIPT_PATH/selenium/docker-compose.selenium.yml"; then
    echo "Failed to do a fresh install"
    return 1
  fi
  if ! docker_compose exec mediawiki ./selenium-preparation.sh apply_patch; then
    echo "Failed to apply patch"
    return 1
  fi
  if ! docker_compose exec mediawiki ./selenium-preparation.sh prepare_node; then
    echo "Failed to prepare node"
    return 1
  fi
}

DOCKER_CHROMIUM_NOVNC_PATH="$SCRIPT_PATH/docker-chromium-novnc"

prepare_docker_chromium_novnc() {
  cd "$SCRIPT_PATH" || {
    echo "Could not change directory to $SCRIPT_PATH"
    return 1
  }
  if ! git submodule update --init --recursive; then
    echo "Failed to update git submodule"
    return 1
  fi
  sleep 1
  CHROMIUM_VERSION=$(docker_compose exec -u root mediawiki /usr/bin/node "./puppeteer-chromium-version-finder.js")
  echo "$CHROMIUM_VERSION"
  cd "$DOCKER_CHROMIUM_NOVNC_PATH" || {
    echo "Could not change directory to $DOCKER_CHROMIUM_NOVNC_PATH"
    return 1
  }
  if ! CHROMIUM_VERSION="$CHROMIUM_VERSION" ./script.sh fresh_install; then
    echo "Failed to perform fresh install"
    return 1
  fi
  return 0
}

is_mediawiki_selenium_ready() {
  # are all mediawiki containers up
  if ! are_containers_running "mediawiki-mediawiki-1" "mediawiki-mediawiki-web-1" "mediawiki-mediawiki-jobrunner-1"; then
    return 1
  fi
  # is MW_SERVER value from docker-compose.selenium.yml in use by mediawiki-mediawiki-1 container?
  if ! is_container_env_var_set "mediawiki-mediawiki-1" "MW_SERVER" "http://mediawiki-mediawiki-web-1:8080"; then
    return 1
  fi
  return 0
}

is_docker_chromium_novnc_automation_ready() {
  # are novnc files present?
  if is_dir_empty "$DOCKER_CHROMIUM_NOVNC_PATH"; then
    return 1
  fi
  # is novnc container running?
  if ! is_container_running "docker-chromium-novnc-novnc-1"; then
    return 1
  fi
  # is novnc url available?
  if [ "$(get_response_code http://localhost:8088)" -ne 200 ]; then
    return 1
  fi
  # is chromium container running?
  if ! is_container_running "docker-chromium-novnc-chromium-1"; then
    return 1
  fi
  # is chromium set for automation?
  cd "$DOCKER_CHROMIUM_NOVNC_PATH" || {
    echo "Could not change directory"
    return 1
  }
  if [ "$(docker compose exec chromium curl --retry 10 --retry-delay 10 --write-out '%{http_code}' --silent --output /dev/null localhost:9222 2>/dev/null)" -ne 200 ]; then
    return 1
  fi
  return 0
}

ensure_selenium_ready() {
  local start
  start=$(date +%s)

  if ! is_mediawiki_selenium_ready; then
    if ! confirm_action "Mediawiki needs to be prepared for Selenium. This will perform a fresh install. Do you wish to continue"; then
      exit 1
    fi
    echo "Preparing Mediawiki container for Selenium by adding Node and setting its MW_SERVER env var..."
    if ! prepare_mediawiki_for_selenium; then
      echo "Failed to prepare Mediawiki for Selenium"
      exit 1
    fi
  fi

  if ! is_mediawiki_selenium_ready; then
    echo "Unable to prepare Mediawiki for Selenium"
    exit 1
  fi

  if ! is_docker_chromium_novnc_automation_ready; then
    if ! confirm_action "Chromium / noVNC containers need to be prepared for Selenium. Do you wish to continue"; then
      exit 1
    fi
    echo "Preparing Chromium / noVNC containers for Selenium..."
    if ! prepare_docker_chromium_novnc; then
      echo "Failed to prepare Chromium / noVNC containers for Selenium"
      exit 1
    fi
  fi

  if ! is_docker_chromium_novnc_automation_ready; then
    echo "Unable to prepare Chromium / noVNC containers for Selenium"
    exit 1
  fi

  sleep 2
  connect_network_to_container "docker-chromium-novnc_default" "mediawiki-mediawiki-1"
  connect_network_to_container "docker-chromium-novnc_default" "mediawiki-mediawiki-web-1"

  print_duration_since_start "$start" "ensure_selenium_ready took %d minutes and %d seconds"
  cd "$DOCKER_CHROMIUM_NOVNC_PATH" || {
    echo "Could not change directory"
    return 1
  }
  ./script.sh view_novnc
}

run_selenium_tests() {
  ensure_selenium_ready
  docker_compose exec mediawiki npx wdio /var/www/html/w/tests/selenium/wdio.conf.override.js
}

run_selenium_test_file() {
  ensure_selenium_ready
  docker_compose exec mediawiki npx wdio /var/www/html/w/tests/selenium/wdio.conf.override.js --spec /var/www/html/w/tests/selenium/specs/user.js
}

run_selenium_test_wildcard() {
  ensure_selenium_ready
  docker_compose exec mediawiki npx wdio /var/www/html/w/tests/selenium/wdio.conf.override.js --spec /var/www/html/w/tests/selenium/specs/**/*.js
}

run_selenium_test() {
  ensure_selenium_ready
  docker_compose exec mediawiki npx wdio /var/www/html/w/tests/selenium/wdio.conf.override.js --spec /var/www/html/w/tests/selenium/specs/page.js --logLevel debug --mochaOpts.grep 'should be creatable'
}

run_selenium_extensions_tests() {
  ensure_selenium_ready
  "$SCRIPT_PATH/extensions/installer.sh" install_all
  docker_compose exec mediawiki npx wdio "/var/www/html/w/tests/selenium/wdio.conf.override.js" --spec "/var/www/html/w/extensions/*/tests/selenium/specs/**/*.js"
}

run_selenium_extension_tests() {
  ensure_selenium_ready
  "$SCRIPT_PATH/extensions/installer.sh" install CheckUser
  docker_compose exec mediawiki npx wdio "/var/www/html/w/tests/selenium/wdio.conf.override.js" --spec "/var/www/html/w/extensions/CheckUser/tests/selenium/specs/**/*.js"
}

run_selenium_extension_test() {
  ensure_selenium_ready
  "$SCRIPT_PATH/extensions/installer.sh" install CheckUser
  docker_compose exec mediawiki npx wdio "/var/www/html/w/tests/selenium/wdio.conf.override.js" --spec "/var/www/html/w/extensions/CheckUser/tests/selenium/specs/checkuser.js" --logLevel debug --mochaOpts.grep 'Should show target input'
}

"$@"
