#!/bin/bash

source "./common/utility.sh"

./shellto m php maintenance/run.php ./maintenance/runJobs.php 2>&1 | verboseOrDotPerLine "Finishing queued jobs"

./shellto mysql tar cvfz /var/lib/mysql-backups/mysql.backup.$(date '+%Y-%m-%d_%H-%M-%S%z-%Z').gz var/lib/mysql 2>&1 | verboseOrDotPerLine "Creating MySQL backup"