#!/bin/bash

source "./common/utility.sh"

if [ -z "$1" ]; then
    echo "Error: No backup file specified"
    echo "Usage: $0 <path-to-backup-file>"
    exit 1
fi

BACKUP_ZIP_PATH=$1

if [ -d "mysql-data" ]; then
    rm -rf mysql-data/*
fi

mkdir -p mysql-data

tar -C mysql-data --strip-components=3 -xzvf $BACKUP_ZIP_PATH 2>&1 | verboseOrDotPerLine "Restoring from MySQL backup"

docker compose restart mysql  2>&1 | verboseOrDotPerLine "Restarting MySQL container"