#!/bin/bash

source "./config"
source "./shell-utilities/utilities.sh"

open_special_version_page() {
  if [ "${SILENT:-0}" = "1" ]; then
    return
  fi
  open_url_when_available "$SPECIAL_VERSION_URL"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  open_special_version_page "$@"  
fi
