#!/bin/bash

source "./config"
source "./common/utility.sh"

prepare() {
  if [ -n "$MEDIAWIKI_PATH" ] && [ -d "$MEDIAWIKI_PATH" ]; then
    docker run --rm \
      -v "$MEDIAWIKI_PATH:/data" \
      -u root \
      alpine sh -c "find /data -print0 | xargs -0 -P \$(nproc) chown -h -f $(id -u):$(id -g)" \
    2>&1 | verboseOrDotPerLine "Ensuring host user can reset/remove files"
  fi

  if ! clone_or_recursively_reset "$GIT_CLONE_BASE_URL/core.git" "$MEDIAWIKI_PATH"; then
    echo "Failed to clone or reset MediaWiki. Exiting."
    exit 1
  fi
  echo -e "" > "$SCRIPT_PATH/common/docker-compose.components.yml"
  echo "$MW_ENV" >.env
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  prepare "$@"
fi