#!/bin/bash

source "./config"
source "./common/utility.sh"
source "./docker/docker.sh"

delete_mediawiki_folder() {
  if [ -n "$MEDIAWIKI_PATH" ] && [ -d "$MEDIAWIKI_PATH" ]; then
    if ! rm -rf "$MEDIAWIKI_PATH"; then
      docker run --rm \
        -v "$MEDIAWIKI_PATH:/data" \
        -u root \
        alpine sh -c "find /data -print0 | xargs -0 -P \$(nproc) chown -h -f $(id -u):$(id -g)" \
      2>&1 | verboseOrDotPerLine "Ensuring host user can reset/remove files"
      rm -rf "$MEDIAWIKI_PATH"
    fi
  fi
}

remove() {
  if ! confirm_action "Are you sure you want to delete mediawiki containers and EVERYTHING in \"$MEDIAWIKI_PATH\""; then
    exit 1
  fi
  docker compose -p mediawiki down --remove-orphans 2>&1 | verboseOrDotPerLine "Docker compose down"
  docker image rm mediawiki-web.selenium:1.0 mediawiki.extras:1.0 2>&1 | verboseOrDotPerLine "Docker image rm" || true
  delete_mediawiki_folder
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  remove "$@"
fi
