#!/bin/bash

source "./config"
source "./common/utility.sh"
source "./docker/docker.sh"

remove() {
  if ! confirm_action "Are you sure you want to delete mediawiki containers and EVERYTHING in \"$MEDIAWIKI_PATH\""; then
    exit 1
  fi
  docker compose -p mediawiki down --remove-orphans 2>&1 | verboseOrDotPerLine "Docker compose down"
  docker image rm mediawiki-web.selenium:1.0 mediawiki.extras:1.0 2>&1 | verboseOrDotPerLine "Docker image rm" || true
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  remove "$@"
fi
