#!/bin/bash

reports="AbuseFilter 0 0 0
AdvancedSearch 0 0 1
AntiSpoof 0 0 1
CampaignEvents 0 0 0
CheckUser 0 0 0
CirrusSearch 0 0 1
Cite 0 0 1
CodeMirror 0 0 1
Collection 0 0 1
ContactPage 0 0 0
Echo 0 0 1
Elastica 0 0 1
ElectronPdfService 0 0 1
EventBus 0 0 1
EventLogging 0 0 1
EventStreamConfig 0 0 1
FileImporter 0 0 1
GlobalBlocking 0 0 1
GlobalWatchlist 0 0 0
IPInfo 0 0 1
Math 0 0 0
MobileFrontend 0 0 1
Newsletter 0 0 0
PageImages 0 0 1
Phonos 0 0 1
Popups 0 0 1
RelatedArticles 0 0 0
SecurityApi 0 0 1
TextExtracts 0 0 1
UploadWizard 0 0 1
UrlShortener 0 0 1
VisualEditor 0 0 1
WikimediaEvents 0 0 1
WikimediaMessages 0 0 1
MinervaNeue 0 0 1
MonoBook 0 0 1
Timeless 0 0 1
Vector 0 0 1
WikimediaApiPortal 0 0 1"

echo "--------------------------------------------------------------------------------"
printf "%-19s%-14s%-8s%-20s\n" "Manifest" "fresh_install" "install" "run_selenium_tests"
echo "--------------------------------------------------------------------------------"

while IFS= read -r line; do
    printf "%-19s%-14s%-8s%-20s\n" $line
done <<< "$reports"