#!/bin/bash

set -eu

source "./common/utility.sh"

report_bug() {
  open_url_when_available "https://phabricator.wikimedia.org/maniphest/task/edit/form/default/?title=Quickstart+Bug&description=Bug+Description&projects[]=mediawiki-quickstart"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  report_bug "$@"
fi