#!/bin/bash

reports=()
report1=(Echo 0 0 0)
reports+=("${report1[*]}")
report2=(Vector 0 0 1)
reports+=("${report2[*]}")

echo "--------------------------------------------------------------------------------"
echo "Manifest fresh_install install run_selenium_tests"
echo "--------------------------------------------------------------------------------"
for report in "${reports[@]}"; do
    echo "$report"
done
echo "--------------------------------------------------------------------------------"
