#!/bin/bash

source "./config"
source "./common/npm-dependencies.sh"

run_jest() {
  ensure_npm_ready
  ./shellto w sh -c "npm run jest"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_jest "$@"
fi
