#!/bin/bash

source "./config"

run_parser_tests() {
  cd "$MEDIAWIKI_PATH" && docker compose exec -u "$HOST_UID:$HOST_GID" mediawiki php tests/parser/parserTests.php
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_parser_tests "$@"
fi