#!/bin/bash

source "./config"

run_php_unit_test_group() {
  local testgroup=$1

  if [ -z "$testgroup" ]; then
    echo "Please provide a test group"
    exit 1
  fi
  ./shellto m composer phpunit -- --group "$testgroup" --testdox
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_php_unit_test_group "$@"
fi
