#!/bin/bash

source "./common/container-readiness.sh"

run_qunit() {
  fresh_install_if_containers_not_running
  docker compose up --no-deps qunit
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_qunit "$@"
fi
