#!/bin/bash

source "./config"

run_php_unit_test_path() {
  local testpath=$1

  if [ -z "$testpath" ]; then
    echo "Please provide a test path"
    exit 1
  fi
  ./shellto m composer phpunit -- "$testpath" --testdox
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_php_unit_test_path "$@"
fi
