#!/bin/bash

source "./common/container-readiness.sh"

run_qunit(){
  fresh_install_if_containers_not_running
  install_node_dependencies
  # At the moment QUnit test runs headless
  ./shellto w sh -c "FIREFOX_BIN=\$(echo /usr/bin/firefox-esr) npm run qunit"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_qunit "$@"
fi