#!/bin/bash

source "./selenium/selenium.sh"
source "./common/utility.sh"

run_selenium_tests() {
  ensure_selenium_ready

  local file_path
  file_path=${1:-"tests/selenium/specs/**/*.js"}
  local test_name
  test_name=${2:-".*"}
  local log_level
  log_level=${3:-"error"}
  # logLevel can be one of these: ( trace | debug | info | warn | error | silent ) https://webdriver.io/docs/configurationfile/

  docker cp "./selenium/wdio.conf.override.js" \
    mediawiki-mediawiki-web-1:/var/www/html/w/tests/selenium/wdio.conf.override.js

  docker exec -it \
    -u root \
    -e DISPLAY=mediawiki-novnc-1:0 \
    mediawiki-mediawiki-web-1 npx wdio "/var/www/html/w/tests/selenium/wdio.conf.override.js" \
      --spec "/var/www/html/w/$file_path" \
      --logLevel "$log_level" \
      --mochaOpts.grep "$test_name"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  if [ "${SILENT:-0}" -ne 1 ]; then
    open_url_when_available "http://localhost:8086/vnc_lite.html?autoconnect=true" &
  fi
  run_selenium_tests "$@"
fi