#!/bin/bash

source "./selenium/selenium.sh"
source "./common/utility.sh"

run_selenium_tests() {
  ensure_selenium_ready || exit 1

  local component_path=${1:-""}

  ./shellto \
    $([[ "${SILENT:-0}" == "1" ]] || echo "-it") \
    -e DISPLAY=mediawiki-novnc-1:0 \
    -e NODE_PATH=/var/www/html/w/node_modules \
    -w "/var/www/html/w/${component_path}" \
    w bash -c '
      source /var/www/html/w/.env
      export CHROME_PATH
      npm run selenium-test
    '
    # npx wdio "tests/selenium/wdio.conf.js" --config "/var/local/wdio.conf.override.js"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  if [ "${SILENT:-0}" -ne 1 ]; then
    open_url_when_available "http://localhost:8086/vnc_lite.html?autoconnect=true" &
  fi
  run_selenium_tests "$@"
fi