#!/bin/bash

source "./docker-compose-wrapper.sh"
source "./selenium/selenium.sh"

run_selenium_extension_test() {
  ensure_selenium_ready
  "$SCRIPT_PATH/extensions/installer.sh" install Echo
  docker_compose exec -u root mediawiki npx wdio "/var/www/html/w/tests/selenium/wdio.conf.override.js" --spec "/var/www/html/w/extensions/Echo/tests/selenium/specs/echo.js" --logLevel debug --mochaOpts.grep 'alerts and notices are visible'
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  run_selenium_extension_test "$@"
fi
