#!/bin/bash

# Thin wrapper around 'docker compose exec' allowing more
# concise invocation of shell commands in Mediawiki's
# containers
#
# Sets user, which callers can override by supplying their
# own '-u', since the last '-u' will take precedent
#
# Reminder: this script should NOT inspect or have knowledge
# of flags passed to it. Remember - "thin wrapper"

source "./config"

args=()

# Replace container shorthand character with full container name
for arg in "$@"; do
  case "$arg" in
    w) args+=("mediawiki-web") ;;
    m) args+=("mediawiki") ;;
    j) args+=("mediawiki-jobrunner") ;;
    n) args+=("novnc") ;;
    e) args+=("elasticsearch") ;;
    *) args+=("$arg") ;;  # Preserve all other arguments as-is
  esac
done

# Append 'sh' if ONLY the container is specified
if [ "${#args[@]}" -eq 1 ]; then
  args+=("sh")
fi

cd "$MEDIAWIKI_PATH" || { echo "Failed to cd to $MEDIAWIKI_PATH"; exit 1; }

# echo "docker compose exec -u \"$HOST_UID:$HOST_GID\" ${args[@]}" >> debug.txt
docker compose exec -u "$HOST_UID:$HOST_GID" "${args[@]}"