#!/bin/bash

source "./config"
source "./common/utility.sh"
source "./docker/docker.sh"
source "./use_skin"
source "./open_special_version_page"
source "./import_extra_local_settings"

start() {
  if ! is_container_present "mediawiki-mediawiki-1"; then
    docker compose up -d 2>&1 | verboseOrDotPerLine "Docker compose up" || exit 1

    ./shellto -u root m sh -c 'chmod 777 /var/local/composer'
    ./shellto -u root m sh -c 'chmod 777 /var/local/npm'
    ./shellto -u root w chown -R "$(id -u):$(id -g)" /var/local
    ./shellto m composer install 2>&1 | verboseOrDotPerLine "Composer install"
    ./shellto \
      -e MW_DBTYPE \
      -e MW_DBPATH \
      -e MW_DBPORT \
      -e MW_DBSERVER \
      -e MW_DBNAME \
      -e MW_DBUSER \
      -e MW_DBPASS \
      m sh -c 'php maintenance/run.php install \
      --server "$MW_SERVER" \
      --scriptpath="$MW_SCRIPT_PATH" \
      --dbtype "${MW_DBTYPE:-sqlite}" \
      --dbpath "${MW_DBPATH:-/var/www/html/w/cache/sqlite}" \
      ${MW_DBSERVER:+--dbserver "$MW_DBSERVER"} \
      ${MW_DBNAME:+--dbname "$MW_DBNAME"} \
      ${MW_DBUSER:+--dbuser "$MW_DBUSER"} \
      ${MW_DBPASS:+--dbpass "$MW_DBPASS"} \
      ${MW_DBPORT:+--dbport "$MW_DBPORT"} \
      --lang "$MW_LANG" \
      --pass "$MW_PASS" \
      --skins "" \
        "$MW_SITENAME" "$MW_USER"' 2>&1 | verboseOrDotPerLine "php maintenance/run.php install"
    ./shellto m /var/local/node-preparation.sh install_node_dependencies 2>&1 | verboseOrDotPerLine "Installing Mediawiki core Node dependencies"

    sleep 2
    import_extra_local_settings 2>&1 | verboseOrDotPerLine "Importing extra local settings"
    if [[ "${SKIP_SKIN:-0}" != "1" ]]; then
      use_skin "Vector"
    else
    	open_special_version_page
    fi
    return 0
  fi

  if ! is_container_running "mediawiki-mediawiki-1"; then
    docker compose up -d  2>&1 | verboseOrDotPerLine "Docker compose up -d"
    sleep 1
  fi
  wait_until_url_available $SPECIAL_VERSION_URL 30 2>&1 | verboseOrDotPerLine "Waiting for Mediawiki page availability"
  local wait_status=${PIPESTATUS[0]}
  if [ "$wait_status" -ne 0 ]; then
    printf "\e[31mUnable to open '$SPECIAL_VERSION_URL'\e[0m\n"
    printf "\e[31mOpening troubleshooting section of 'README.md'...\e[0m\n"
    open_url_when_available "https://gitlab.wikimedia.org/repos/test-platform/mediawiki-quickstart#troubleshooting"
    exit 1
  fi
  sleep 1
  open_special_version_page | verboseOrDotPerLine "Opening 'Special:Version' page"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  start "$@"
fi
