#!/bin/bash

source "./config"
source "./common/utility.sh"
source "./docker/docker.sh"
source "./use_skin"
source "./open_special_version_page"
source "./import_extra_local_settings"

start() {
  if ! is_container_present "mediawiki-mediawiki-1"; then
    cd "$MEDIAWIKI_PATH"
    docker compose up -d 2>&1 | verboseOrDotPerLine "Docker compose up" || exit 1
    docker compose exec -u "$HOST_UID:$HOST_GID" mediawiki composer install 2>&1 | verboseOrDotPerLine "Composer install"  
    docker compose exec -u "$HOST_UID:$HOST_GID" mediawiki /docker/install.sh 2>&1 | verboseOrDotPerLine "/docker/install.sh"
    sleep 2
    import_extra_local_settings 2>&1 | verboseOrDotPerLine "Importing extra local settings"
    if [[ "${SKIP_SKIN:-0}" != "1" ]]; then
      use_skin "Vector"
    else
    	open_special_version_page
    fi
    return 0
  fi

  if ! is_container_running "mediawiki-mediawiki-1"; then
    cd "$MEDIAWIKI_PATH" && docker compose up -d  2>&1 | verboseOrDotPerLine "Docker compose up -d"
    sleep 1
  fi
  wait_until_url_available $SPECIAL_VERSION_URL
  sleep 1
  open_special_version_page
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  start "$@"
fi
