#!/bin/bash

source "./config"
source "./shell-utilities/utilities.sh"

stop() {
  if [ ! -d "$MEDIAWIKI_PATH" ]; then
    return
  fi
  if [ ! -f "$MEDIAWIKI_PATH/docker-compose.yml" ]; then
    return
  fi
  cd "$MEDIAWIKI_PATH" && docker compose stop 2>&1 | verboseOrDotPerLine "Docker compose stop"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  stop "$@"
fi
