#!/bin/bash

source "./config"
source "./docker/docker-compose-wrapper.sh"

stop() {
  if [ ! -d "$MEDIAWIKI_PATH" ]; then
    return
  fi
  if [ ! -f "$MEDIAWIKI_PATH/docker-compose.yml" ]; then
    return
  fi
  docker_compose stop
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  stop "$@"
fi
