#!/bin/bash

source "./config"
source "./make_skin_default"

use_skin() {
  cd "$SCRIPT_PATH"
  local skin_name
  skin_name="$1"
  local skin_path
  skin_path="skins/$1"
  SILENT=1 ./install "$skin_path"
  if ! make_skin_default "$skin_name"; then
    echo "Failed to make "$skin_name" default"
    exit 1
  fi
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  use_skin "$@"
fi