#!/bin/bash

source "./extensions/common.sh"

declare -a INSTALLED_EXTENSIONS=()

install() {
  if ! _ensure_containers_running; then
    exit 1
  fi
  INSTALLED_EXTENSIONS=()
  for extension in "$@"; do
    local manifest
    manifest="$(_get_script_path)/manifests/$extension.yml"
    if [[ -f "$manifest" ]]; then
      _install_from_manifest "$manifest"
    else
      echo "No corresponding manifest file found for extension '$extension', skipping..."
    fi
  done
  _install_php_and_node_dependencies
  _rebuild_localization_cache
  _run_bash_for_installed_extensions
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install "$@"
fi