#!/bin/bash

source "./extensions/common.sh"

declare -a INSTALLED_EXTENSIONS=()

install_all() {
  if ! _ensure_containers_running; then
    exit 1
  fi
  INSTALLED_EXTENSIONS=()
  local extension_dir
  for extension_dir in "$(_get_script_path)/manifests"/*; do
    local extension_name=$(basename "$extension_dir")
    _install_from_manifest "$extension_name"
  done
  _install_php_and_node_dependencies
  _run_bash_for_installed_extensions
  _rebuild_localization_cache
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install_all "$@"
fi