#!/bin/bash

source "./extensions/common.sh"

declare -a INSTALLED_EXTENSIONS=()

install() {
  if ! _ensure_containers_running; then
    exit 1
  fi
  INSTALLED_EXTENSIONS=()
  for extension in "$@"; do
    local manifest_path="$(_get_manifest_path "$extension")"
    if [[ -d "$manifest_path" ]]; then
      _install_from_manifest "$extension"
    else
      echo "No corresponding manifest folder found for extension '$extension', skipping..."
    fi
  done
  _install_php_and_node_dependencies
  _run_bash_for_installed_extensions
  _rebuild_localization_cache
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install "$@"
fi