#!/bin/bash

source "./skins/common.sh"

install_all() {
  if ! _ensure_containers_running; then
    exit 1
  fi
  for manifest in "$(_get_script_path)/manifests/"*.yml; do
    _install_from_manifest "$manifest"
  done
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install_all "$@"
fi