#!/bin/bash

docker run -it --rm \
  --platform linux/amd64 \
  --env-file .env \
  -v "$(pwd)/main.tf:/workspace/main.tf" \
  -v "$(pwd)/vps.cloudconfig.yml:/workspace/vps.cloudconfig.yml" \
  -v "$(pwd)/generate_imports_file:/workspace/generate_imports_file" \
  ghcr.io/montehurd/mediawiki-docker-images/tofu:latest