FROM docker-registry.wikimedia.org/dev/bookworm-apache2:1.0.0

COPY ./install-browser-for-puppeteer-core.js /var/local

COPY ./node-preparation.sh /var/local
COPY ./install-chrome-dependencies.sh /var/local

RUN set -ex && \
    apt-get update && \
    apt-get install -y xz-utils && \
    /var/local/node-preparation.sh ensure_node_major_version_installed 18 && \
    /var/local/install-chrome-dependencies.sh

WORKDIR /var/www/html/w
