#!/bin/bash

source "/var/local/common/utility.sh"

set -eu

install_node_dependencies() {
  if ! /var/local/installer/configure_npm_workspaces 2>&1 | verboseOrDotPerLine "Hoisting all skin/extension Node dependency satisfaction to MW core, if needed"; then
    echo "Failed to configure MW core 'package.json' to use NPM workspaces wildcard paths for skins/extensions. Exiting"
    return 1
  fi

  if ! [ -f "package.json" ]; then
    echo "Expected 'package.json' not found in '$(pwd)'"
    return 1
  fi

  if ! npm install --legacy-peer-deps 2>&1 | verboseOrDotPerLine "Npm install"; then
    echo "NPM install failed. Exiting"
    return 1
  fi
  return 0
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install_node_dependencies "$@"
fi
