#!/bin/bash

source "/var/local/installer/common.sh"

declare -a INSTALLED_COMPONENTS=()

install() {
  INSTALLED_COMPONENTS=()
  for component_path in "$@"; do
    _install_from_manifest "$component_path"
  done
  _install_php_and_node_dependencies
  _run_bash_for_installed_components
  _rebuild_localization_cache
  _import_page_dumps_for_installed_components
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install "$@"
fi