#!/bin/bash

source "/var/local/common/utility.sh"

install_node_dependencies_for_components() {
  local components=("$@")
  local component=""
  for component in "${components[@]}"; do
    cd ~
    cd "$component"
    /var/local/installer/install_node_dependencies 2>&1 | verboseOrDotPerLine "Installing Node dependencies for '$component'"
  done
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install_node_dependencies_for_components "$@"
fi
