#!/bin/bash

set -eu

source "/var/local/common/utility.sh"

if [ -z "${GIT_CLONE_BASE_URL:-}" ]; then
  echo "Error: GIT_CLONE_BASE_URL environment variable must be set"
  exit 1
fi

_get_component_type() {
  local component_path="$1"
  dirname "$component_path"
}

_get_component_name() {
  local component_path="$1"
  basename "$component_path"
}

_get_manifest_path() {
  local component_path="$1"
  echo "/var/local/$component_path"
}

_ensure_containers_running() {
  if ! [ "$(docker inspect -f '{{.State.Running}}' mediawiki-mediawiki-1)" = "true" ]; then
    echo "MediaWiki container is not running"
    return 1
  fi
  return 0
}

_get_component_local_settings_path() {
  local component_path="$1"
  echo "$(_get_manifest_path "$component_path")/LocalSettings.php"
}

_clone_component() {
  local component_path="$1"
 
  local clone_depth="--depth=${CLONE_DEPTH:-2}"
  if [ "${CLONE_DEPTH:-1}" -eq 0 ]; then
    local clone_depth=""
  fi

  local repository="$GIT_CLONE_BASE_URL/$component_path"

  if ! clone_git_repo "$repository" "$component_path" true "${BRANCH:-}"; then
    echo "Failed to clone repository '$repository'"
    exit 1
  fi
}

_import_page_dumps_for_installed_components() {
    local folders=()
    for component_path in "$@"; do
        local pages_folder="$(_get_manifest_path "$component_path")/pages"
        if [ -d "$pages_folder" ]; then
            folders+=("$pages_folder")
        fi
    done
    if [ ${#folders[@]} -gt 0 ]; then
        bash /import_page_xml.sh "${folders[@]}"
    fi
}

_run_bash_for_installed_components() {
  for component_path in "$@"; do
    cd ~
    _run_bash_from_manifest "$component_path" 2>&1 | verboseOrDotPerLine "Running '$component_path/setup.sh' if found"
  done
  cd ~
}

_run_bash_from_manifest() {
  local component_path="$1"
  local setup_script="$(_get_manifest_path "$component_path")/setup.sh"
  echo -e "Looking for '${setup_script}'"
  if [ -f "${setup_script}" ]; then
    echo "Running setup script '${setup_script}'"
    chmod +x "${setup_script}"
    cd ~
    "${setup_script}"
  else
    echo "No '${setup_script}' found, skipping..."
  fi
}

_install_php_and_node_dependencies() {
  if ! /var/local/installer/install_php_dependencies; then
    echo "Failed to install PHP dependencies"
    exit 1
  fi
  if ! /var/local/installer/run_mediawiki_maintenance_update; then
    echo "Mediawiki maintenance update failed. Exiting"
    return 1
  fi
  if ! /var/local/installer/install_node_dependencies; then
    echo "Failed to install Node dependencies"
    exit 1
  fi
}

_rebuild_localization_cache() {
  sleep 1
  php maintenance/rebuildLocalisationCache.php --force --threads=$(getconf _NPROCESSORS_ONLN) 2>&1 | verboseOrDotPerLine "Rebuild Mediawiki localization cache"
}

_components_with_compose() {
  for dir in "$@"; do
    if [[ -f "/var/local/$dir/docker-compose.yml" ]]; then
      echo "$dir"
    fi
  done
}

_update_component_docker_compose_includes() {
  local components_file="/var/local/common/docker-compose.components.yml"
  local components
  components=$(_components_with_compose "$@")
  if [[ -z "$components" ]]; then
    return 0
  fi
  local contents
  for component in $components; do
    contents=$(cat "$components_file")
    _yq '.include[0].path = (.include[0].path // []) + ["../'$component'/docker-compose.yml"] | .include[0].path |= unique' "$contents" > "$components_file"
  done
  return 0
}

_link_components() {
  for component_path in "$@"; do
    echo "" >> Components.php
    echo "# Local settings for '$(_get_component_name "$component_path")' $(_get_component_type "$component_path")" >> Components.php
    local local_settings_path="$(_get_component_local_settings_path "$component_path")"
    echo "require_once \"$local_settings_path\";" >> Components.php
  done
}

install() {
  # Return special exit code 2 to indicate no components needed installation
  (( $# )) || return 2

  for component_path in "$@"; do
    local local_settings_path="$(_get_component_local_settings_path "$component_path")"
    printf "\n\033[34mInstalling '%s'\033[0m\n" "$(_get_component_name "$component_path")"
    if [ ! -f "$local_settings_path" ]; then
      printf "    \e[31mRequired '%s' does not exist\e[0m\n\
      There is a folder for skins and a folder for extensions\n\
      Ensure your component's manifest folder is in the correct one,\n\
      containing its own 'LocalSettings.php'\n\
  \e[31mExiting\e[0m\n" "$local_settings_path"
      exit 1
    fi
  done

  # Export function for parallel execution
  export -f _clone_component
  export -f clone_git_repo
  export -f verboseOrDotPerLine
  export -f print_duration_since_start
  # export -f map_gerrit_to_github

  # Export variables for parallel execution
  export GIT_CLONE_BASE_URL
  export CLONE_DEPTH
  export BRANCH

  # Build commands for parallel execution
  local CLONE_COMMANDS=""
  for component_path in "$@"; do
    CLONE_COMMANDS+="_clone_component \"$component_path\"
"
  done

  # Execute clone commands in parallel
  parallel_process "$CLONE_COMMANDS"

  # Linking needs to happen in-order (ie not parallel/async)
  _link_components "$@"

  _install_php_and_node_dependencies
  _run_bash_for_installed_components "$@"
  if [[ "${SKIP_LOCALIZATION_CACHE_REBUILD:-0}" != "1" ]]; then
    _rebuild_localization_cache
  fi
  if [[ "${SKIP_PAGE_IMPORT:-0}" != "1" ]]; then
    _import_page_dumps_for_installed_components "$@"
  fi
  _update_component_docker_compose_includes "$@"
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  # echo "REQUESTED COMPONENTS: $@"
  COMPONENTS=$(/var/local/common/hydrate_dependencies_list "$@")
  # echo "HYDRATED COMPONENTS: $COMPONENTS"
  UNINSTALLED_COMPONENTS=$(php maintenance/run.php /var/local/installer/FilterOutInstalledComponents --components "$COMPONENTS")
  # echo "UNINSTALLED COMPONENTS: $UNINSTALLED_COMPONENTS"
  install $UNINSTALLED_COMPONENTS
fi