#!/bin/bash

# set -x

source "./installer/common.sh"
source "./open_special_version_page"

declare -a INSTALLED_COMPONENTS=()

install() {
  if ! _ensure_containers_running; then
    exit 1
  fi
  INSTALLED_COMPONENTS=()
  for component_path in "$@"; do
    _install_from_manifest "$component_path"
  done
  _install_php_and_node_dependencies
  _run_bash_for_installed_components
  _rebuild_localization_cache
  _import_page_dumps_for_installed_components
	open_special_version_page
}

if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
  install "$@"
fi